### ISSUE TITLE
schedule display continues to append

### ISSUE THREAD

**Issue by waynew** [MichPCX/Heinrichy#1]
Steps to repro:

- start up heinrichy
- create a single schedule item
- exit the schedule module
- type schedule again
- exit the schedule module
- observe that "Today's schedule" now has multiple copies of each event on the schedule
- repeat as many times as desired

Not a big deal, and I may end out fixing this myself, but it's something that exists!

**Comment by MichPCX** [comment]
Sorry for late reply, and thanks for pointing out this bug, I've did few hours of tests before uploading first prototype but I haven't noticed this one. I'll try to fix it today or tomorrow!

**Comment by MichPCX** [comment]
Fixed in _0.23Alpha release!

**Comment by waynew** [comment]
👍 excellent!
