### ISSUE TITLE
Enhancement: Support Python3 (or both Python2 and 3)

### ISSUE THREAD

**Issue by waynew** [MichPCX/Heinrichy#2]
Right now Heinrichy only supports Python2, I'd love to see Python 3 support, or even 2 *and* 3 support. On Arch Linux the default python is Python3, and other Linuxes are headed that way. It shouldn't take too much effort to produce support for both versions. I'm certainly willing to put forth some effort to make that happen.

**Comment by fcgomes92** [comment]
+1

**Comment by MichPCX** [comment]
Interesting, I didn't think that python 3 and python 2 are that similar. I'll try to do few tests before committing it but I think it should work well with both versions. Thanks for your effort!

**Comment by waynew** [comment]
Yeah - there's also the [`six`](https://pythonhosted.org/six/) module that helps with 2*3 compatibility.

**Comment by MichPCX** [comment]
The most recent update to Heinrichy brings python 2 & python 3 compatibility, it took me a while to test everything and change bits but finally there it is  :thumbsup:
