### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by waynew** [MichPCX/Heinrichy#3]
Currently Heinrichy has no license file - AFAIK that means it's copyrighted by you. If you intend to make this open source, you should add a license - MIT or BSD are good choices if you want people to be free to use the software however they see fit. GPL or AGPL could be a good fit if you want to **require** that people share their changes to heinrichy.

**Comment by MichPCX** [comment]
Totally forgot about that one, thanks

**Comment by waynew** [comment]
👍 works for me
