### ISSUE TITLE
Change config file format

### ISSUE THREAD

**Issue by waynew** [MichPCX/Heinrichy#4]
Having the config file as a `.py` file makes it a bit awkward - if we want to make changes to our config then we have to make sure we don't accidentally commit our config file. No bueno.

The [configparser](https://docs.python.org/3/library/configparser.html) module could be a good choice, or even just using `json.load`. The thing I like about configparser is that you can give it several different filenames to try and read and it will just ignore those that it can't find. So we could do something like search for config files in:

- `/etc/heinrichy.conf`
- `~/.heinrichyrc`
- `~/.config/heinrichy/config`
- somewhere provided on the command line

Or somewhere else even?

**Comment by MichPCX** [comment]
I am working on rather big update to Heinrichy which will have config with new format and all I need to do is to polish the code, add few small features and I will upload everything in few days. Thanks for the idea!

**Comment by MichPCX** [comment]
I've just uploaded new update!
