### ISSUE TITLE
Convert to use cmd module instead of print

### ISSUE THREAD

**Issue by waynew** [MichPCX/Heinrichy#5]
Currently heinrichy just uses the `print` and `(raw_)input`. The [`cmd` module](https://docs.python.org/3/library/cmd.html) provides tons of flexibility and simple support for:

- handling different prompts
- catching EOF, rather than typing `exit`

It could definitely make the code a lot more reasonable.

**Comment by MichPCX** [comment]
For now, Heinrichy will stay with `print()` & `input()` functions as I want to focus on the things that will improve Heinirchy to make it more popular with community but maybe in the future when I will focus on optimizing it, I will definitely consider `cmd module`!  Closing for now...
